import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "../styles/globals.scss";
import { notoSerifThai, rubik } from "@/styles/fonts/fonts";
import DefaultLayout from "@/components/default-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${rubik.className} ${notoSerifThai.className}`}>
      <body className={inter.className}>
        <Providers>
          {/* <DefaultLayout> */}
            {children}
          {/* </DefaultLayout> */}
        </Providers>
      </body>
    </html>
  );
}
